### ISSUE TITLE
Problem in step 2 "build"

### ISSUE THREAD

**Issue by guyshahaf** [koba/overhead-camera-people-counter#3]
I'm trying to test the project on ubuntu 16.04.
All step 1 "1. Installing Dependencies" went smooth with no issues.
In step 2 "2. Build" when I run the command: "cmake --build /build" I'm getting the error: "Error: /build is not a directory". I'm running the command from the "release" directory.

What an I missing?

Thanks in advanced,
  Guy

**Comment by agurod42** [comment]
Hello @guyshahaf,

Gonna try in an ubuntu env. In the meantime could you try with the following sequence of commands:

```
mkdir build
cd build
cmake ..
cd ..
```

**Comment by ArnaudBernaille** [comment]
Hello agurodriguez and guyshahaf  :)
 I have the same probleme than guyshahaf and i've tried your commandes : it still don't work.
(I'm on Armbian ubuntu 16.04)

I've also tried to enter : cmake .
You will see that lots of libraries are missing. I will try to install them.
If you have other ideas I will be thankfull.
Thanks in advanced

**Comment by agurod42** [comment]
Hi @yhamster,

Just tried in a fresh ubuntu environment and it works just fine for me. Could you please attach the result of the cmake execution?

**Comment by ArnaudBernaille** [comment]
Hello agurodriguez

I've changed my OS before seeing your message so I can't tell you what the error message was. 
But I've tried with a new os witch is armv71.

I've followed the steps of the tuto (including  mkdir build, cd build, cmake .., cd ..)  and when I enter cmake --build/ build : /var/pi/opencv/release/build does not appear to contain CMakeLists.txt.

When I enter "cmake --build build/" : error : couldn't load cache. 

When I enter "cmake ." : it's says "no for package for XXX" many many time for many packages. 

"cmake -build." seems to solve the probleme ( you should try this guyshahaf).

I think that your tuto is not totally complete : between step 1 and 2 you didn't said where do we have to go. I think that we need to reach your source file and don't stay in opencv. 
Moreover according to the teminal the version of opencv is not compatible with the app. 

 Thanks in advanced

**Comment by ArnaudBernaille** [comment]
I think it's finally working but I have an other question : Is your code able to run with a camera and not only a pre-loaded video ? 
If yes how do you give to the program the video flow ? I've trie ./people-counter /dev/video0 but it is not working.

**Comment by agurod42** [comment]
Hi @yhamster, I'm glad you could figure it out. 

As you suggested, I'll add the "go back to src folder step" after opencv build is done.

Regarding to your question you can find more info here: https://github.com/agurodriguez/overhead-camera-people-counter/issues/2
